package lookup

//GetResponseHTTP Function
func GetTrxField(rc string) string {

	return GetTrxFieldMAP(rc)
}

//GetResponseMAP Function
func GetTrxFieldMAP(rc string) string {
	MapperrDesc := map[string]string{
		// "creationDate":                             "creationDate",
		// "valueDate":                                "valueDate",
		// "bookingDate":                              "bookingDate",
		// "parentAccountKey":                         "parentAccountKey",
		// "type":                                     "type",
		// "amount":                                   "amount",
		// "currencyCode":                             "currencyCode",
		// "affectedAmounts.fundsAmount":              "affectFundsAmount",
		// "affectedAmounts.interestAmount":           "affectInterestAmount",
		// "affectedAmounts.feesAmount":               "affectFeesAmount",
		// "affectedAmounts.overdraftAmount":          "affectOverdraftAmount",
		// "affectedAmounts.overdraftFeesAmount":      "affectOverdraftFeesAmount",
		// "affectedAmounts.overdraftInterestAmount":  "affectOverdraftInterestAmount",
		// "affectedAmounts.technicalOverdraftAmount": "affectTechnicalOverdraftAmount",
		// "affectedAmounts.technicalOverdraftInterestAmount": "affectTechnicalOverdraftInterestAmount",
		// "affectedAmounts.fractionAmount":                   "affectFractionAmount",
		// "accountBalances.totalBalance":                     "accTotalBalance",
		// "userKey":                                          "userKey",
		// "transactionDetails.transactionChannelKey":         "TransactionChannelKey",
		// "transactionDetails.transactionChannelId":          "TransactionChannelId",
		// "_ktpAddress.ktpCity":                              "ktpCity",
		// "_ktpAddress.ktpProvince":                          "ktpProvince",
		// "_ktpAddress.ktpPostalCode":                        "ktpPostalCode",
		// "_ktpAddress.ktpRtRw":                              "ktpRtRw",
		// "_ktpAddress.ktpSubDistrict":                       "ktpSubDistrict",
		// "_ktpAddress.ktpVillage":                           "ktpVillage",
		// "_ktpAddress.ktpAddress":                           "ktpAddress",

		// "_personalIdData.personalIdNumber":         "personalIdNumber",
		// "_personalIdData.personalNpwpNumber":       "personalNpwpNumber",
		// "_personalIdData.personalIdType":           "personalIdType",
		// "_personalIdData.personalBranch":           "personalBranch",
		// "_personalIdData.urlImageKtp":              "urlImageKtp",
		// "_personalIdData.personalIdDateOfIssue":    "personalIdDateOfIssue",
		// "_personalIdData.urlImageSelfie":           "urlImageSelfie",
		// "_personalIdData.personalIdExpireDate":     "personalIdExpireDate",
		// "_personalIdData.personalReferralCode":     "personalReferralCode",
		// "_personalIdData.personalMarketingOfficer": "personalMarketingOfficer",

		// "_occupationInfo.personalOccupation":    "personalOccupation",
		// "_occupationInfo.companyName":           "companyName",
		// "_occupationInfo.personalMonthlyIncome": "personalMonthlyIncome",
		// "_occupationInfo.personalTypeOfWork":    "personalTypeOfWork",

		// "_customerData.personalMothersName":   "personalMothersName",
		// "_customerData.personalMaritalStatus": "personalMaritalStatus",
		// "_customerData.personalCitizenship":   "personalCitizenship",
		// "_customerData.birthPlace":            "birthPlace",
		// "_customerData.personalReligion":      "personalReligion",
		// "_customerData.personalScoringCust":   "personalScoringCust",

		// "_companyAddress.companyAddressVillage":     "companyAddressVillage",
		// "_companyAddress.companyAddress":            "companyAddress",
		// "_companyAddress.companyAddressSubDistrict": "companyAddressSubDistrict",
		// "_companyAddress.companyAddressPostalCode":  "companyAddressPostalCode",
		// "_companyAddress.companyAddressProvince":    "companyAddressProvince",
		// "_companyAddress.companyAddressPhoneNumber": "companyAddressPhoneNumber",
		// "_companyAddress.companyAddressCity":        "companyAddressCity",
		// "_companyAddress.companyAddressRtRw":        "companyAddressRtRw",

		// "_mailingAddress.mailingAddress":              "mailingAddress",
		// "_mailingAddress.mailingAddressVillage":       "mailingAddressVillage",
		// "_mailingAddress.mailingAddressProvince":      "mailingAddressProvince",
		// "_mailingAddress.mailingAddressRtRw":          "mailingAddressRtRw",
		// "_mailingAddress.MailingAddressPostalCode":    "MailingAddressPostalCode",
		// "_mailingAddress.mailingAddressSubDistrict":   "mailingAddressSubDistrict",
		// "_mailingAddress.mailingRecipientPhoneNumber": "mailingRecipientPhoneNumber",
		// "_mailingAddress.mailingAddressCity":          "mailingAddressCity",
	}
	val, err := MapperrDesc[rc]
	if !err {
		val = string(rc)
	}

	return val
}

//GetBankInstName Function
func GetBankInstName(InstID string) string {
	MapperrDesc := map[string]string{
		"014": "Bank BCA",
		"008": "Bank Mandiri",
		"009": "Bank BNI",
		"427": "Bank BNI Syariah",
		"002": "Bank BRI",
		"451": "Bank Syariah Mandiri",
		"022": "Bank CIMB Niaga",
		"147": "Bank Muamalat",
		"213": "Bank Tabungan Pensiunan Nasional (BTPN)",
		"422": "Bank BRI Syariah",
		"200": "Bank Tabungan Negara (BTN)",
		"013": "Permata Bank",
		"011": "Bank Danamon",
		"016": "Bank BII Maybank",
		"426": "Bank Mega",
		"153": "Bank Sinarmas",
		"950": "Bank Commonwealth",
		"028": "Bank OCBC NISP",
		"441": "Bank Bukopin",
		"536": "Bank BCA Syariah",
		"026": "Bank Lippo",
		"031": "Citibank",
		"789": "Indosat Dompetku",
		"110": "Bank Jabar dan Banten (BJB)",
		"111": "Bank DKI",
		"112": "BPD DIY",
		"113": "Bank Jateng",
		"114": "Bank Jatim",
		"115": "BPD Jambi",
		"116": "BPD Aceh, BPD Aceh Syariah",
		"117": "Bank Sumut",
		"118": "Bank Nagari",
		"119": "Bank Riau",
		"120": "Bank Sumsel Babel",
		"121": "Bank Lampung",
		"122": "Bank Kalsel",
		"123": "Bank Kalimantan Barat",
		"124": "Bank Kalimantan Timur dan Utara",
		"125": "Bank Kalteng",
		"126": "Bank Sulsel dan Barat",
		"127": "Bank Sulut Gorontalo",
		"128": "Bank NTB, NTB Syariah",
		"129": "BPD Bali",
		"130": "Bank NTT",
		"131": "Bank Maluku Malut",
		"132": "Bank Papua",
		"133": "Bank Bengkulu",
		"134": "Bank Sulawesi Tengah",
		"135": "Bank Sultra",
		"003": "Bank Ekspor Indonesia",
		"019": "Bank Panin",
		"020": "Bank Arta Niaga Kencana",
		"030": "American Express Bank LTD",
		"032": "JP. Morgan Chase Bank, N.A",
		"033": "Bank of America, N.A",
		"034": "ING Indonesia Bank",
		"911": "Link Aja",
		"037": "Bank Artha Graha Internasional",
		"039": "Bank Credit Agricole Indosuez",
		"040": "The Bangkok Bank Comp. LTD",
		"041": "The Hongkong & Shanghai B.C. (Bank HSBC)",
		"042": "The Bank of Tokyo Mitsubishi UFJ LTD",
		"045": "Bank Sumitomo Mitsui Indonesia",
		"046": "Bank DBS Indonesia",
		"047": "Bank Resona Perdania",
		"048": "Bank Mizuho Indonesia",
		"050": "Standard Chartered Bank",
		"052": "Bank ABN Amro",
		"053": "Bank Keppel Tatlee Buana",
		"054": "Bank Capital Indonesia",
		"057": "Bank BNP Paribas Indonesia",
		"023": "Bank UOB Indonesia",
		"059": "Korea Exchange Bank Danamon",
		"425": "Bank BJB Syariah",
		"061": "Bank ANZ Indonesia",
		"067": "Deutsche Bank AG.",
		"068": "Bank Woori Indonesia",
		"069": "Bank OF China ",
		"076": "Bank Bumi Arta",
		"087": "Bank Ekonomi",
		"088": "Bank Antardaerah",
		"089": "Bank Haga",
		"093": "Bank IFI",
		"095": "Bank JTRUST",
		"097": "Bank Mayapada",
		"145": "Bank Nusantara Parahyangan",
		"146": "Bank of India Indonesia",
		"151": "Bank Mestika Dharma",
		"152": "Bank Metro Express (Bank Shinhan Indonesia)",
		"157": "Bank Maspion Indonesia",
		"159": "Bank Hagakita",
		"161": "Bank Ganesha",
		"162": "Bank Windu Kentjana",
		"164": "Halim Indonesia Bank (Bank ICBC Indonesia)",
		"166": "Bank Harmoni International",
		"167": "Bank QNB Kesawan (Bank QNB Indonesia)",
		"212": "Bank Himpunan Saudara 1906",
		"405": "Bank Swaguna",
		"459": "Bank Bisnis Internasional",
		"466": "Bank Sri Partha",
		"472": "Bank Jasa Jakarta",
		"484": "Bank Bintang Manunggal",
		"485": "Bank MNC / Bank Bumiputera",
		"490": "Bank Yudha Bhakti",
		"494": "Bank BRI Agro",
		"498": "Bank Indomonex (Bank SBI Indonesia)",
		"501": "Bank Royal Indonesia",
		"503": "Bank Alfindo (Bank National Nobu)",
		"506": "Bank Syariah Mega",
		"513": "Bank Ina Perdana",
		"517": "Bank Harfa",
		"520": "Prima Master Bank",
		"521": "Bank Persyarikatan Indonesia",
		"525": "Bank Akita",
		"526": "Liman International Bank",
		"531": "Anglomas Internasional Bank",
		"523": "Bank Dipo International (Bank Sahabat Sampoerna)",
		"535": "Bank Kesejahteraan Ekonomi",
		"542": "Bank Artos IND",
		"547": "Bank Purba Danarta",
		"548": "Bank Multi Arta Sentosa",
		"553": "Bank Mayora Indonesia",
		"555": "Bank Index Selindo",
		"559": "Centratama Nasional Bank",
		"566": "Bank Victoria International",
		"562": "Bank Fama Internasional",
		"564": "Bank Mandiri Taspen Pos",
		"567": "Bank Harda",
		"688": "BPR KS",
		"945": "Bank Agris",
		"946": "Bank Merincorp",
		"947": "Bank Maybank Indocorp",
		"948": "Bank OCBC – Indonesia",
		"949": "Bank CTBC (China Trust) Indonesia",
	}
	return MapperrDesc[InstID]
}
